import prisma from '../../lib/db';
import { fetchPrometheusMetrics } from '../utils/prometheus';
import { analyzeMetrics } from '../utils/ai';

export async function checkServiceForAnomalies(serviceId: string) {
  try {
    const successPoints = await fetchPrometheusMetrics(serviceId, 'probe_success');
    const durationPoints = await fetchPrometheusMetrics(serviceId, 'probe_duration_seconds');

    if (!successPoints.length && !durationPoints.length) {
      console.log(`[Anomaly] No metrics found for service ${serviceId}. Skipping.`);
      return;
    }

    // 1. Evaluate Rule-based Anomalies
    const latestSuccess = successPoints.length > 0 ? successPoints[successPoints.length - 1]![1] : 1;
    const isDown = latestSuccess === 0;

    let isLatencySpiked = false;
    if (durationPoints.length > 0) {
      const latestDuration = durationPoints[durationPoints.length - 1]![1];
      const previousDurations = durationPoints.slice(0, -1).map(p => p[1]);
      
      if (previousDurations.length > 0) {
        const avgDuration = previousDurations.reduce((a, b) => a + b, 0) / previousDurations.length;
        isLatencySpiked = latestDuration > avgDuration * 2.5; // Trigger if latency is > 2.5x avg
      }
    }

    if (!isDown && !isLatencySpiked) {
      console.log(`[Anomaly] Service ${serviceId} metrics are normal.`);
      return;
    }

    console.log(`[Anomaly] Detected rule-based anomaly for ${serviceId}. Proceeding to AI Analysis...`);

    let aiResult;
    try {
      aiResult = await analyzeMetrics(serviceId, isDown, isLatencySpiked, {
        durationSeconds: durationPoints,
        success: successPoints,
      });
    } catch (err) {
      console.error(`[Anomaly] AI Analysis failed for ${serviceId}. Using fallback rules.`, err);
      aiResult = {
        isAnomaly: true,
        reason: isDown ? 'Service probe_success is 0 (Downtime).' : 'Latency is significantly higher than historical average.',
        severity: isDown ? 'CRITICAL' : 'HIGH',
        suggested_action: 'Investigate application logs and network immediately. (Generated by fallback)'
      };
    }

    if (aiResult.isAnomaly) {
      console.log(`[Anomaly] AI Confirmed Anomaly [${aiResult.severity}]:`, aiResult.reason);

      // Save Incident
      await prisma.incident.create({
        data: {
          title: `Anomaly Detected: ${isDown ? 'Downtime' : 'Latency Spike'}`,
          description: aiResult.reason,
          type: isDown ? 'downtime' : 'latency',
          severity: aiResult.severity,
          details: {
            suggested_action: aiResult.suggested_action,
            ai_raw_metadata: aiResult,
          },
          serviceId: serviceId,
        }
      });

      // Save Anomaly Log
      await prisma.anomalyLog.create({
        data: {
          metric: isDown ? 'probe_success' : 'probe_duration_seconds',
          value: null, // we use raw_data to store the payload
          raw_data: {
            probe_success: successPoints,
            probe_duration_seconds: durationPoints
          },
          serviceId: serviceId,
        }
      });
    }

  } catch (error) {
    console.error(`[Anomaly] Full pipeline error for service ${serviceId}:`, error);
    throw error; // Worker can retry
  }
}
