version: '3.8'
services:
  # The OpenTelemetry Collector (The Router)
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318" # OTLP HTTP receiver port
      - "8889:8889" # MUST EXPOSE THIS: Prometheus metrics port

  # Jaeger (For Traces)
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI

  # Prometheus (For Metrics)
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./:/etc/prometheus # Mount directory to avoid macOS VirtioFS "resource deadlock avoided" bug
    ports:
      - "9090:9090" # Prometheus UI

  # The AI Anomaly Detector
  anomaly-detector:
    build: ../anomaly_detction # Path to the folder containing your Dockerfile
    container_name: ai-watcher
    depends_on:
      - prometheus # Ensure Prometheus starts first
    volumes:
      # This saves the incident reports from inside the container to your local machine!
      - ../anomaly_detction/reports:/app/reports
    environment:
      # Connect directly to the Prometheus container on the internal Docker network
      - PROMETHEUS_URL=http://prometheus:9090/api/v1/query_range

